apiVersion: v1
kind: Secret
metadata:
  name: fordspec-api-secrets
  namespace: fordspec
type: Opaque
stringData:
  JWT_SECRET: "<preencher-via-cofre>"
  DATA_ENC_KEYS: "<preencher-via-cofre>"
  PSEUDO_SALT: "<preencher-via-cofre>"
  METRICS_TOKEN: "<preencher-via-cofre>"
  DATABASE_URL: "<preencher-via-cofre>"
